---
- name: Set Postfix option hostname
  debconf: name=postfix question="postfix/mailname" value="{{server_hostname}}" vtype="string"

- name: Set Postfix option type as internet site
  debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"

- name: Install Postfix
  apt: name={{item}} state=latest
  with_items:
    - postfix
    - mailutils

